### ISSUE TITLE
How do you set this on Windows? 

### ISSUE THREAD

**Issue by CristiVlad25** [VincentHch/vscodex#2]
Where do you specify or how do you config environment variable?

**Comment by VincentHch** [comment]
https://docs.oracle.com/en/database/oracle/machine-learning/oml4r/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html

**Comment by CristiVlad25** [comment]
I already did that, and it still doesnt work:

![image](https://user-images.githubusercontent.com/17044663/130771082-d91cf8e9-7485-403a-a42b-bfd4ac995631.png)

**Comment by VincentHch** [comment]
You must completely restart vscode (or restart your computer)

**Comment by CristiVlad25** [comment]
Obviously, I did this and it still didn't work.

**Comment by CristiVlad25** [comment]
Note, it's OPENAI_API_KEY and not OPEN_AI_API_KEY, I looked into the source file of the extension.

You can make changes to the readme file:

```
In Windows, set environment variable for a key:

1. Open cmd
2. Type: SET OPENAI_API_KEY=<your_api_key>

If it doesn't work, disable and re-enable the extension in VSCODE, and/or restart Windows.
```

**Comment by VincentHch** [comment]
Fixed, thanks.
