### ISSUE TITLE
Install on windows.

### ISSUE THREAD

**Issue by monkeydust** [VincentHch/vscodex#9]
Hi, how do you install on windows. Get this error:

****
npm ERR! missing script: build:install
npm ERR!
npm ERR! Did you mean one of these?
npm ERR!     preinstall
npm ERR!     postinstall

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ravlo\AppData\Roaming\npm-cache\_logs\2021-08-31T09_51_15_831Z-debug.log

**Comment by VincentHch** [comment]
Hi, I changed the installation commands, it should work (maybe sudo will be needed for some commands)
